/**
 * Static demo mode (VITE_DEMO=1): pre-recorded traces generated by the real
 * backend engine, bundled so the deployed frontend works without a server.
 */

import bigoBubbleSort from "./demo/bigo_bubble_sort.json";
import bubbleSort from "./demo/bubble_sort.json";
import reverseList from "./demo/reverse_list.json";
import twoSum from "./demo/two_sum.json";
import type { ComplexityResult, TraceStep } from "./types";

export interface DemoSample {
  key: string;
  label: string;
  code: string;
  functionName: string;
  argsText: string;
  timeline: TraceStep[];
  bigO?: ComplexityResult;
}

export const IS_DEMO = import.meta.env.VITE_DEMO === "1";

export const DEMO_SAMPLES: DemoSample[] = [
  {
    ...(bubbleSort as unknown as DemoSample),
    bigO: bigoBubbleSort as unknown as ComplexityResult,
  },
  twoSum as unknown as DemoSample,
  reverseList as unknown as DemoSample,
];
